### ISSUE TITLE
ブロックコードとコメントアウト

### ISSUE THREAD

**Issue by KeenS** [rust-lang-ja/the-rust-programming-language-ja#13]
ブロックコードをコメントアウトするのがどうもgitbookと相性良くないようです。今のところブロックコードはコメントアウトせず削除することで対応しています。

幸い、コード中に出てくるコメントの分量はそこまで多くないので大丈夫ですが、いずれは対応を考える必要があります。

**Comment by Nnwww** [comment]
ではPRを投げる側でコードブロックを削除しておいた方が良いですか?

**Comment by KeenS** [comment]
はい。おねがいします。他に良い方法(コメント部分だけ抽出してコメントアウトしておくとか)があるならその方がいいのですがとりあえずは削除ということでお願いします。

**Comment by yohhoy** [comment]
ブロックコードのコメントアウトとは、具体的にどのような記述でしょうか？下記のようなもの？

```
<!-- Is this `block code`? -->
```

**Comment by KeenS** [comment]
それは問題ないです。バッククォートを3つ使った別行立ての方です。

``````
<!-- ```
   this is the block code
  ``` -->
``````

**Comment by KeenS** [comment]
#28 にてそれっぽい解決策発見。

``` rust
# // let x = "foo" // this is a commet
let x = "foo" // これはコメントです。
```

のようにするとHTMLの表示上は原文は見えない。

@Nnwww @yohhoy @tatsuya6502 @ykomatsu @dalance 
この方式でどうでしょうか。

**Comment by ykomatsu** [comment]
[「Documentation as tests」](http://rust-lang-ja.github.io/the-rust-programming-language-ja/1.6/book/documentation.html#documentation-as-tests)で使われている方法ですね。
いいと思います。

**Comment by Nnwww** [comment]
良いと思います。

**Comment by tatsuya6502** [comment]
https://github.com/rust-lang-ja/the-rust-programming-language-ja/issues/13#issuecomment-177376372

> ```
> # // let x = "foo" // this is a commet
> let x = "foo" // これはコメントです。
> ```
> 
> この方式でどうでしょうか

試してみました。
- rustbook で生成した HTML → 英文が表示されない
- play.rust-lang.org のコードエディタ → 英文も和文もコードコメントとして表示される

いいですね。この方法に賛成します。

**Comment by KeenS** [comment]
ありがとうございます。既存のものの変換とCONTRIBUTINGの変更しますね。

**Comment by KeenS** [comment]
done
