### ISSUE TITLE
Rust by example を翻訳したいと思うのですが

### ISSUE THREAD

**Issue by joemphilips** [rust-lang-ja/the-rust-programming-language-ja#131]
翻訳ありがとうございます。Rustの勉強をする上で助かりました。
こちらの[Rust by example](https://github.com/rust-lang/rust-by-example/blob/master/CONTRIBUTING.md)
を和訳しようと考えています。せっかくなのでRust-lang-ja内に新しいリポジトリを作るのが良いと思うのですが、inviteしてもらうことは可能でしょうか。
ダメなら、
@tatsuya6502 
さんに作っていただくか、私のリポジトリで勝手に行おうかと考えています。

**Comment by KeenS** [comment]
> せっかくなのでRust-lang-ja内に新しいリポジトリを作るのが良いと思う

私もそう思います。 @tatsuya6502 さんがいいようならinviteしますがいかがですか？

**Comment by tatsuya6502** [comment]
@joemphilips ご提案、ありがとうございます！　Rust-lang-ja内に新しいリポジトリを作ることに賛成します。

@KeenS はい。ぜひ @joemphilips さんを invite してください。

**Comment by KeenS** [comment]
inviteしました。何かあったらまた言って下さい。

**Comment by joemphilips** [comment]
ありがとうございます。
