### ISSUE TITLE
独自ドメインの取得を行いたいと思います。

### ISSUE THREAD

**Issue by joemphilips** [rust-lang-ja/the-rust-programming-language-ja#147]
[rust-by-example-jaでシンタックスハイライトが動作しない問題があった](https://github.com/rust-lang-ja/rust-by-example-ja/issues/7)のですが、

[中国語](https://rustwiki.org/rust-by-example/)と[英語](http://rustbyexample.com/)と比較した結果、独自ドメインを取得すれば解決するのではないかと考えました。

そこで、私の方で取得しようかと考えているのですが、せっかくなのでorganization全体のものを取ろうかと考えています。つまり`rust-lang-ja`でDNSを取得し、`rust-lang-ja/rust-by-example`と`rust-lang-ja/the-rust-programming-language`で文書を表示という形です。

ご意見いただければ幸いです。

@KeenS @tatsuya6502

**Comment by KeenS** [comment]
@joemphilips 
ドメインを取ること自体には反対はないです。

しかしシンタックスハイライトの問題はconfigにrootを設定したら直りそうな気もしますが…
https://github.com/GitbookIO/gitbook/blob/master/docs/config.md

**Comment by KeenS** [comment]
@joemphilips 
私も調べてみたらgitbook側での解決は難しそうですね。
ドメイン自体あると嬉しいですし良いと思います。

**Comment by joemphilips** [comment]
`rust-lang-ja.org`でドメイン名を取得しました。使い方はおいおい考えていこうかと思います。

**Comment by KeenS** [comment]
ありがとうございます。

**Comment by tatsuya6502** [comment]
@joemphilips 返信遅くなりました。ドメインを取得していただき、ありがとうございました。嬉しいです！
