### ISSUE TITLE
Markdownの*などについて

### ISSUE THREAD

**Issue by ykomatsu** [rust-lang-ja/the-rust-programming-language-ja#18]
CONTRIBUTING.mdでは、

> Markdownのマークアップ記法の前後は空白/空行を空けることを基本とするが、厳密でなくてもよい。

ということになっていますが、`*`などは前後に空白を入れないと、`rustbook`が認識してくれないようです。

http://rust-lang-ja.github.io/the-rust-programming-language-ja/1.6/book/effective-rust.html

**Comment by KeenS** [comment]
たまに空けなくても認識してくれるものがあるので分かってやっているなら「厳密でなくてもよい」としたのですがrustbookを手元で動かせる人が少なそうなので厳密にした方が良いかもしれませんね。
少し考えます。

**Comment by KeenS** [comment]
#26 #29 にて変更済み/修正中。
