### ISSUE TITLE
eBook

### ISSUE THREAD

**Issue by KeenS** [rust-lang-ja/the-rust-programming-language-ja#187]
メモ

The Rust Programming Language 日本語訳をe-bookにしてみる - Qiita
http://qiita.com/hmikisato/items/cc6700c09b28fdc7d9e1

**Comment by y-yu** [comment]
はじめまして。

上記の記事を読みまして、勝手ながら上記の記事とおおむね同じ方法で日本語版のPDFファイルを作成して`gh-pages`ブランチにデプロイするようにした`.travis.yml`を書いてみました。

https://github.com/y-yu/trpl-ja-pdf

### 変更点
- 原著ではLaTeXの処理系にXeLaTeXを用いていたがLuaLaTeXへ変更した
- Qiitaの記事では欧文用のクラスファイルで組版していたが、日本語用のクラスファイルに変更した

**Comment by KeenS** [comment]
吉村さんはじめまして。
PDFの生成まで自動化されたんですね。非常に素晴らしいですね。
そちらのレポジトリへREADMEからリンクを貼っても宜しいでしょうか。

**Comment by y-yu** [comment]
@KeenS さん。

>  そちらのレポジトリへREADMEからリンクを貼っても宜しいでしょうか。

はい、かまいません。
ただ、このリポジトリを私個人が管理するというのも微妙なので、rust-lang-jaオーガニゼーションに譲渡する方がよいかなと思っています。

**Comment by KeenS** [comment]
githubって権限のないレポジトリにtransfer ownership出来ましたっけ？出来るのならそれが一番早いのですがそうでなければrust-lang-jaでフォークするか @y-yu さんをorganizationに入れるかしようと思います。
CC @tatsuya6502

**Comment by y-yu** [comment]
とりあえず、rust-lang-jaにtransfer ownershipしてみる、ということでよいでしょうか。

**Comment by tatsuya6502** [comment]
@y-yu さん、contribution ありがとうございます！

> rust-lang-jaにtransfer ownershipしてみる、ということでよいでしょうか。

はい。まずは transfer ownership を試してみましょう。

うろ覚えですが、transfer 先の organization に権限がない場合は、organization の管理者向けに通知メールが来て、そこから承認する形になっていたと思います。（私は今日はこれから外出してしまうので、夜まで対応できないのですが、 @KeenS さんがもし日中 お時間があったら、承認をお願いします）

**Comment by y-yu** [comment]
transfer ownershipを試したのですが、

> You don’t have admin rights to rust-lang-ja 

とGitHubに言われるので、forkするか私がadminにならないといけないようです。

**Comment by tatsuya6502** [comment]
@y-yu transfer ownership はダメでしたか。試していただき、ありがとうございました。

fork ですと GitHub の search 結果に表示されないので、以下のページの手順に従って、（fork ではなく）リポジトリを複製しました。
- https://help.github.com/articles/duplicating-a-repository/

複製先のレポジトリはこちらになります。
- https://github.com/rust-lang-ja/trpl-ja-pdf

README.md のリンク先や、Travis CI からの gh-pages への push 設定などは、おいおい修正していきます。

あとは、the-rust-programming-language-ja の master ブランチにコミットがあった時に、PDF を自動生成（＝CI を自動起動）したいので、その方法を考えないといけないですね。trpl-ja-pdf の内容をまるごと、the-rust-programming-language-ja に取り込むかもしれません。

**Comment by tatsuya6502** [comment]
**参考：リポジトリの移管や複製について**
- **移管(Transferring a repository)**
  - https://help.github.com/articles/about-repository-transfers
  - https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account
  - 上の２つのヘルプページの内容を合わせると、以下のような仕組みらしい（合っているかは自信なし）
  - 別の個人アカウントへの移管では、移管先のアカウントの持ち主が承認操作を行えばよい(?)
  - organization への移管は、移管元の所有者が organization のメンバーでないといけない。ヘルプページには書かれていないが、恐らくリポジトリの作成権限が必要(?)
- **複製(Duplicating a repository)**
  - https://help.github.com/articles/duplicating-a-repository
- **Fork 後に親レポジトリを削除したり、非公開にしたりするとどうなるか？**
  - https://help.github.com/articles/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility/#deleting-a-public-repository
  - Fork の１つが親レポジトリに昇格する。どの fork が選ばれるかは説明なし。

**Comment by y-yu** [comment]
@tatsuya6502 さん。

お返事が遅くなりました。
リポジトリの複製ありがとうございます。
いくつか設定しなければならないと思うのですが、私が参考にしたWebサイトを貼っておきます。
もし何かありましたら、遠慮なく質問していただきたいと思います。

### Travis CIによる自動デプロイ

こちらのサイトを参考に、デプロイ用の秘密鍵を暗号化してリポジトリに埋め込んで、それを用いています。

http://blog.eiel.info/blog/2014/02/18/github-push-from-travis/

**Comment by KeenS** [comment]
こちら [rust-lang-ja/trpl-ja-pdf](https://github.com/rust-lang-ja/trpl-ja-pdf) が出来たのでクローズします。
