### ISSUE TITLE
不安定なフィーチャ->不安定な新機能

### ISSUE THREAD

**Issue by lv7777** [rust-lang-ja/the-rust-programming-language-ja#194]
フィーチャーというのは直感的に理解しにくい気がします。
ここは和製英語を使わずそのまま新機能と訳したほうがいい気がします。

**Comment by KeenS** [comment]
前提として、featureといったときにRustの機能としてあるフィーチャ(`#[feature(..)]` を使うことで有効になるオプトインの機能群)と普通の名詞のfeatureがあって、前者をフィーチャ、後者を機能（など）と訳して区別しています。

それを踏まえた上で「unstable features」を見るとフィーチャと機能両方の意味で使われていると思います。どちらで訳してもいいのですが読みづらいとのことならば新機能の方を採用しましょう。

プルリクを頂けたら取り込みます。

**Comment by lv7777** [comment]
> 前提として、featureといったときにRustの機能としてあるフィーチャ(#[feature(..)] を使うことで有効になるオプトインの機能群)と普通の名詞のfeatureがあって、前者をフィーチャ、後者を機能（など）と訳して区別しています。

なるほど！rustの機能としてあるのですね。
それなら下手に改変しないほうがいいと思います。

**Comment by lv7777** [comment]
閉じます。
対応して頂きありがとうございました。

**Comment by KeenS** [comment]
報告ありがとうございました。
また気付いたことがありましたらissueかプルリク頂けると嬉しいです。
