### ISSUE TITLE
5.1 スタックとヒープ 複雑な例のfの値

### ISSUE THREAD

**Issue by masateruk** [rust-lang-ja/the-rust-programming-language-ja#209]
翻訳の問題ではないのでしょうが、読んでいて気になりましたので起票します。

fの値が→9にならないのは何故なんでしょう？アドレスを辿ると2^30-2になるのはわかるのですが、補足する説明が欲しいと思いました。

**Comment by KeenS** [comment]
ここで答えるのが適切かは分かりませんが。

確かに説明がなくてちょっと分かりづらいですね。これは[`Deref` による型強制](https://rust-lang-ja.github.io/the-rust-programming-language-ja/1.6/book/deref-coercions.html)によるものです。
[std::boxed::Box](https://doc.rust-lang.org/std/boxed/struct.Box.html)が `impl<T> Deref for Box<T> where T: ?Sized {type Target = T}` を実装しているため、 `&i32` を期待する関数のためにRustコンパイラが `&Box<i32>` を `&i32` に変換しています。

以上の説明で大丈夫でしょうか？

**Comment by KeenS** [comment]
こういう質問を気軽に出来る場としてRustの日本ユーザの集るslackが存在するので案内しておきますね。

http://rust-jp.herokuapp.com/

**Comment by masateruk** [comment]
ありがとうございます。いただいた説明で理解できました。これから翻訳の問題でなければslackの方で質問させていただきます。
