### ISSUE TITLE
Help with translating the site?

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang-ja/the-rust-programming-language-ja#226]
Hi there! We're trying to translate the website into Japanese as well: https://github.com/rust-lang/rust-www/pull/628

Would any of you be interested in helping review? Feel free to close this issue, as it's not a bug in the translation of the book, but I didn't know the best way to ask.

**Comment by KeenS** [comment]
That's interesting. I'll review it.

**Comment by KeenS** [comment]
I've got involved
https://github.com/rust-lang/rust-www/pull/690
