### ISSUE TITLE
対訳表のキーワードについて

### ISSUE THREAD

**Issue by ykomatsu** [rust-lang-ja/the-rust-programming-language-ja#24]
対訳表に入っているキーワードの`enum`、`mut`、`struct`については、

> - 構文キーワードなどはそのままアルファベットを使う

という規則から一義的にアルファベットで表記することが決まるので、対訳表からは削除した方がよいように思います。

**Comment by KeenS** [comment]
`struct`と"struct"はちゃんと分ける必要があると示したかったのですが誤解がないなら削除しても良いと思ってます。削除した方が良いですか?

**Comment by ykomatsu** [comment]
英語版では基本的にキーワードをバッククオートでマークアップしていることから、誤解の可能性は低いと思うことと、対訳表が長くなると見難いかなというくらいの理由ですのでお任せします。

**Comment by KeenS** [comment]
分かりました。削除します。
