### ISSUE TITLE
和訳におけるrustupのインストール方法が古い

### ISSUE THREAD

**Issue by Nnwww** [rust-lang-ja/the-rust-programming-language-ja#244]
Getting Started (和訳題: [はじめる(1.9)](https://github.com/rust-lang-ja/the-rust-programming-language-ja/blob/master/1.9/ja/book/getting-started.md))についてです．

[バージョン1.14.0のRust Book](https://github.com/rust-lang/rust/blob/1.14.0/src/doc/book/getting-started.md)の時点でrustup.shからrustup.rsの方式へ変更が行われました．
特に顕著なのがインストール方法であり，

* 1.14.0以前
```curl -sSf https://static.rust-lang.org/rustup.sh | sh```
* 1.14.0以降
``` curl https://sh.rustup.rs -sSf | sh```

となった結果，初めて和訳ドキュメントを訪れた方がインストールに失敗する事態にあります．

特にGetting Startedは重要ですので，最新1.15.0版の更新PRを送りたいと考えています．ですが1.9更新分のレビューが目下進行中のため，どのタイミングでPRを送るのが好ましいか，そもそも1.9更新分のレビュー完了を待つべきか，私には判断が難しい所です．

従ってIssueにて報告させていただきます．

**Comment by KeenS** [comment]
報告ありがとうございます。1.6と1.9に訳注で入れるのが適切かと思います。両者への変更をPR頂けたら取り込みます。

**Comment by KeenS** [comment]
#248 にて対応頂きました。
