### ISSUE TITLE
Rangeの訳をレンジから範囲に

### ISSUE THREAD

**Issue by KeenS** [rust-lang-ja/the-rust-programming-language-ja#272]
See conversations at  #271 
@tatsuya6502 @chikoski

**Comment by KeenS** [comment]
月曜日までに(2017-06-12-00:00:00+0900)返信なければ上記のPRマージします。

**Comment by tatsuya6502** [comment]
遅くなってすみません。これから PR #271 をレビューします。

**Comment by tatsuya6502** [comment]
@KeenS 内容確認しました。対訳表でRangeの訳を「レンジ」から「範囲」に変える旨、賛成します。

**Comment by chikoski** [comment]
私も内容を確認しました。妥当な提案だと思います。
