### ISSUE TITLE
次に翻訳する文書を決める

### ISSUE THREAD

**Issue by KeenS** [rust-lang-ja/the-rust-programming-language-ja#276]
TRPLの2ndエディションがアナウンスされた。 https://github.com/rust-lang/book
@tatsuya6502 さんと内々に話している限りでは 1stの最新版まで追い付いてから2ndに取り掛かる。

**Comment by KeenS** [comment]
別の人が2ndの翻訳を始めている。
https://github.com/hazama-yuinyan/book
公式レポジトリで交渉した上で始めているので2ndの翻訳はこちらが本家になりそう。

**Comment by tatsuya6502** [comment]
その後、2018年8月ごろから、hazama-yuinyan/book の内容を [こちら](https://doc.rust-jp.rs/book/second-edition/) で公開しています。

現在は別のリポジトリ（rust-lang-ja/book-ja）にて、英語版の最新の内容に追従するための作業を実施中です。
- https://github.com/rust-lang-ja/book-ja/milestone/1

本件はクローズします。
