### ISSUE TITLE
Inherentの訳語

### ISSUE THREAD

**Issue by tesaguri** [rust-lang-ja/the-rust-programming-language-ja#283]
[共通の関数呼び出し構文](https://github.com/rust-lang-ja/the-rust-programming-language-ja/blob/master/1.6/ja/book/ufcs.md)と[構文の索引](https://github.com/rust-lang-ja/the-rust-programming-language-ja/blob/master/1.6/ja/book/syntax-index.md)において"inherent"が「継承（された）」と訳されていますが、これはトレイトを介さない実装を指す言葉なので継承（inherit）とは字面が似ているだけで別の概念です。

代わりにどういった訳語を当てるべきなのかは自明な問題ではないですが、よく使われているものとしては「固有」という訳があります（e.g. inherent impl: 固有実装、inherent method: 固有メソッド）。

**Comment by KeenS** [comment]
ありがとうございます。固有がよさそうですね。対応します。
