### ISSUE TITLE
1.9 以降への追従（特に lifetimes.md）

### ISSUE THREAD

**Issue by soramichi** [rust-lang-ja/the-rust-programming-language-ja#287]
現在 rust 1.6 と rust 1.9 の `src/doc/book` をベースに翻訳されていますが、それ以降のバージョンへの追従は行わない予定でしょうか。

特に lifetimes.md には 1.14 で例が追加されてかなり分かりやすくなっていますので、変更部分を追従すると読者にとってかなり助かると思います。
1.9 以降の内容を取り込む方針などあれば教えて頂ければ私から PR することも可能です。

参考
https://github.com/rust-lang/rust/blob/1.14.0/src/doc/book/lifetimes.md
`fn skip_prefix(line: &str, prefix: &str) -> &str` を使った例が追加されています。

**Comment by KeenS** [comment]
issueありがとうございます。
一応次移行の予定は立っています。
https://github.com/rust-lang-ja/the-rust-programming-language-ja/issues/276
ここでは1stを翻訳していくので1.9の翻訳が完了したら次は今のfirstの最新版 https://github.com/rust-lang/book/tree/master/first-edition ですね。その折にはぜひPR下さい。

現状中の人多忙のため翻訳/レビューが動いていなので1.9が終わる見通しは立っていません。もしレビューなどご協力いただけるなら嬉しいです。

**Comment by soramichi** [comment]
なるほど、了解しました。
新しい First edition を翻訳される際には協力させて頂きます。
