### ISSUE TITLE
標準ライブラリのリファレンスへのリンク

### ISSUE THREAD

**Issue by ykomatsu** [rust-lang-ja/the-rust-programming-language-ja#32]
標準ライブラリのリファレンスへのリンクは基本的に相対パスで書かれているようなのですが、これは英語版のURLに置き換えればよいでしょうか。

> 変更前：[bool]: ../std/primitive.bool.html
> 変更後：[bool]: https://doc.rust-lang.org/std/primitive.bool.html

http://rust-lang-ja.github.io/the-rust-programming-language-ja/1.6/book/primitive-types.html#booleans

**Comment by KeenS** [comment]
それは今迷っています。和訳もバージョン毎に本家からドキュメントを持ってきているのでこのレポジトリに含めてしまうのも1つの手かな、とは思っています。
将来APIドキュメントの和訳をするならそちらの方が良さそうですが本家にリンク貼らないのもいかがなものか、という迷いがあります。

**Comment by KeenS** [comment]
@ykomatsu 
考えてみました。
公式のドキュメントは常時アップデートされるのに対してこのドキュメントはバージョン毎に固定しているので公式ドキュメントへのリンクにすると将来不整合が発生する可能性があります。

なので
1. 標準ライブラリのドキュメントもこのレポジトリでホスティングする
2. 余力があればそれも翻訳する（本当に余力があればの話)

で如何でしょうか。

**Comment by ykomatsu** [comment]
いいと思います。
ということはリンクはそのままの形にしておくということでよいでしょうか。

**Comment by KeenS** [comment]
はい、そうです。

**Comment by tatsuya6502** [comment]
https://github.com/rust-lang-ja/the-rust-programming-language-ja/issues/32#issuecomment-177192816

> 1. 標準ライブラリのドキュメントもこのレポジトリでホスティングする

本件ですが、先ほど @KeenS さん作成の以下の PR をマージし、完了しました。いまのところ英語版ではありますが、API ドキュメント等も、このレポジトリでホスティングされるようになってます。
- [APIドキュメント（など）のインポート #128](https://github.com/rust-lang-ja/the-rust-programming-language-ja/pull/128)

@KeenS さん、作業おつかれさまでした！ :star: :star: :star: :star: :star:
