### ISSUE TITLE
進行状況の整理

### ISSUE THREAD

**Issue by ykomatsu** [rust-lang-ja/the-rust-programming-language-ja#44]
どの文書が翻訳済みでどの文書が未翻訳かを一覧する方法があるといいと思います。
- meta-issueを用意する（一般的なmeta-issueの例： dart-lang/sdk#23454）
- Wikiに表を用意する

**Comment by KeenS** [comment]
wikiの方が皆が編集出来て良いんですかね。用意します。

**Comment by KeenS** [comment]
作りました

https://github.com/rust-lang-ja/the-rust-programming-language-ja/wiki/%E7%BF%BB%E8%A8%B3%E9%80%B2%E8%A1%8C%E7%8A%B6%E6%B3%81%E7%AE%A1%E7%90%86%E8%A1%A8

**Comment by ykomatsu** [comment]
ありがとうございます！

**Comment by tatsuya6502** [comment]
ありがとうございます！　これ後ほど、各ページヘのリンクを張って、翻訳が終わるまでの暫定的な **目次** としても使えるようにしておきますね。そうすれば、英語が苦手な人でも読み始められるので。

**Comment by KeenS** [comment]
ありがとうございます。

**Comment by tatsuya6502** [comment]
暫定的な目次の件、対応しました。あと、一番上に簡単な注意書きも付けました。（[ページヘのリンク](https://github.com/rust-lang-ja/the-rust-programming-language-ja/wiki/%E7%BF%BB%E8%A8%B3%E9%80%B2%E8%A1%8C%E7%8A%B6%E6%B3%81%E7%AE%A1%E7%90%86%E8%A1%A8)）

**Comment by KeenS** [comment]
すごい! ありがとうごさいます。
