### ISSUE TITLE
getting-startedの「can be thought　of as」

### ISSUE THREAD

**Issue by ykomatsu** [rust-lang-ja/the-rust-programming-language-ja#60]
@KeenS

https://github.com/rust-lang-ja/the-rust-programming-language-ja/blob/master/1.6/ja/book/getting-started.md

> Tier 1 platforms can be thought of as "guaranteed to build and work".
> 1級のプラットフォームは「ビルド出来かつ動くことを保証する」ものと思えます。
> 
> Tier 2 platforms can be thought of as "guaranteed to build".
> 2級のプラットフォームは「ビルドを保証する」ものと思えます。

自分たちが設定した級について「思え」るというのはちょっと変な気がするので、「されています」くらいの方がよいように思います。

**Comment by KeenS** [comment]
私が最初に訳した部分なのでレビューなしに通ってしまったやつですね :sweat: 
不自然だなと思いつつも原文に忠実に訳しました。下記の要件を要約したのかな、と無理矢理理解していました。

修正のPR投げますね。

**Comment by ykomatsu** [comment]
ありがとうございます。
確認しました。
