### ISSUE TITLE
scopedの訳

### ISSUE THREAD

**Issue by mandel59** [rust-lang-ja/the-rust-programming-language-ja#90]
現時点で、列挙型 https://github.com/rust-lang-ja/the-rust-programming-language-ja/tree/master/1.6/ja/book/enums.md においては、scoped が「スコープされた」と訳されています。これは日本語として変なので、「スコープ化された」という訳にし、TranslationTable に追加することを提案します。（検索したところ、「スコープ化された」は既存の用例があるようです。）

**Comment by keiichiw** [comment]
その箇所を訳したのは私ですが、確かに「スコープ化された」の訳の方が良いように思うので、提案に賛成します。

**Comment by keiichiw** [comment]
PR 出しました。
確認よろしくお願いします。

**Comment by tatsuya6502** [comment]
PR #91 にて対応済み。本件、クローズします。
